version: "3.9"
services:
  couchdb:
    build:
      context: couchdb
      dockerfile: Dockerfile
      # dockerfile relative path is from build context
    volumes: 
      - type: volume
        source: couchdb-data
        target: /opt/couchdb/data
    ports:
      - "0.0.0.0:${COUCHDB_EXTERNAL_PORT}:${COUCHDB_INTERNAL_PORT}"     
      # We are presuming that there is no proxy server on the dev server, so we're not using COUCHDB_PORT here
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD
    networks:
      - conductor-local-dev
  conductor:
    build:
      context: .
    command: "npm run watch"
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:${CONDUCTOR_EXTERNAL_PORT}:${CONDUCTOR_PORT}"
    networks:
      - conductor-local-dev
    environment:
      #  note that some of these are pulled from the environment (.env) 
      #  while others get values here if the value is known for 
      #  docker-compose setup

      - PROFILE_NAME
      
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD
      - COUCHDB_CONTAINER_NAME
      - COUCHDB_PORT
      - COUCHDB_EXTERNAL_PORT
      - COUCHDB_URL=${COUCHDB_PROTOCOL}://${COUCHDB_CONTAINER_NAME}:${COUCHDB_PORT}/

      - COUCHDB_INTERNAL_PORT
      # Where is this server running
      - CONDUCTOR_PROTOCOL
      - CONDUCTOR_PORT
      - CONDUCTOR_EXTERNAL_PORT

      # probably unused?
      - COUCHDB_PUBLIC_URL

      # https://faimsproject.atlassian.net/wiki/spaces/FAIMS3/pages/151846960/FAIMS3+Conductor+build+run+environment+variables

      # optional
      - CLUSTER_ADMIN_GROUP_NAME

      - FAIMS_COOKIE_SECRET

      # public URL for accessing Conductor & CouchDB
      - CONDUCTOR_PUBLIC_URL
      - COMMIT_VERSION

      - CONDUCTOR_AUTH_PROVIDERS
      - CONDUCTOR_EMAIL_HOST_NAME
      - CONDUCTOR_EMAIL_HOST_CONFIG

      - CONDUCTOR_INVITE_DB=${COUCHDB_URL}${CONDUCTOR_INVITE_DB_NAME:-invites}
      - FAIMS_USERDB=${COUCHDB_URL}${FAIMS_USERDB_NAME:-people}

      # https://faimsproject.atlassian.net/wiki/spaces/FAIMS3/pages/151846960/FAIMS3+Conductor+build+run+environment+variables#Authentication-Provider-Specific-environment-variables
      - DATACENTRAL_GROUP_PREFIX
      - DATACENTRAL_CLIENT_ID
      - DATACENTRAL_CLIENT_SECRET
      - HAVE_DATACENTRAL_MANAGE_ROLES=true
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET

      - CONDUCTOR_EMAIL_FROM_ADDRESS
      - CONDUCTOR_EMAIL_TRANSPORTER

      # URLs for apps for this instance
      - WEB_APP_PUBLIC_URL
      - ANDROID_APP_PUBLIC_URL
      - IOS_APP_PUBLIC_URL
networks:
  conductor-local-dev: {}
volumes:
  couchdb-data: